services:
  postgres:
    image: postgres:17
    container_name: bun-auth-postgres
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: